### ISSUE TITLE
Set post author for micropub posts

### ISSUE THREAD

**Issue by aaronpk** [snarfed/wordpress-micropub#10]
It looks like a post author is not set right now. I think you could reasonable assume that the "me" value that the token is granted for can be looked up in the users table, the same way the IndieAuth plugin allows people to sign in to their Wordpress sites using their domain. 

I think this would have the added benefit of being immediately useful for multi-author sites.

**Comment by snarfed** [comment]
@aaronpk makes sense. just to confirm, for a multi-author site, you're expecting people would log into indieauth (and then generate a token) with their user profile url, e.g. https://snarfed.org/author/ryan instead of https://snarfed.org/ ?

**Comment by aaronpk** [comment]
No, not quite. Currently I am able to sign in to caseorganic.com as the "aaronpk" user there by typing in "aaronparecki.com" into the IndieAuth sign-in screen. This is because on my Wordpress account I put aaronparecki.com as my website.

Ideally for a multi-user blog like https://geoloqi.com/blog/ each author would have their own personal home page still, and could use that to sign in.

Feel free to skip the multi-user use case for now if it makes things complicated.

**Comment by snarfed** [comment]
ah true, right. no this is doable.

**Comment by pfefferle** [comment]
We Diskusses that earlier... I use something similar for the indieauth Plugin: https://github.com/pfefferle/wordpress-indieauth/blob/master/indieauth.php#L80

**Comment by snarfed** [comment]
thanks for the suggestion, @pfefferle and @aaronpk!
