### ISSUE TITLE
port to new `mp-*` params

### ISSUE THREAD

**Issue by snarfed** [snarfed/wordpress-micropub#11]
@aaronpk and @dissolve have been iterating on the micropub spec a fair amount. it now uses `mp-*` params for control. we need to port our handling of `url` to `mp-url`, `action` to `mp-action`, and maybe more? there's also `mp-add` and `mp-remove`, among others. see https://indiewebcamp.com/micropub#Syntax

**Comment by snarfed** [comment]
probably worth a full audit of the spec to collect everything we need to do to bring this up to date. cc @dshanske @acegiak @pfefferle @petermolnar @peterwilsoncc in case anyone's interested.

**Comment by dshanske** [comment]
I have been looking at this again. Simple solution is to add a compat function which changes the old param to new.

**Comment by dshanske** [comment]
Re arrays, checking for array values is easy enough.

**Comment by snarfed** [comment]
based on the current spec, `mp-*` are still reserved, but only `mp-syndicate-to` is actually used right now, and we support it. closing.
