### ISSUE TITLE
Syndication Target Code Causing Error

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#114]
The current syndication target code does an array_diff to compare the syndication targets to the syndicate to property. Problem is, if you check the specification, that is an incorrect assumption.

"At a minimum, a syndication target MUST have a uid and human-readable name property. The uid can be any identifier unique to the Micropub endpoint and is not intended to be visible to the end user. The name is intended to be visible to the user in the posting interface, and should be descriptive of the syndication destination."

So, the syndicate-to property will be an array with a set of URLs. The syndication targets should be a multidimensional array.

**Comment by snarfed** [comment]
@dshanske you fixed this, right?

**Comment by dshanske** [comment]
Yes

**Comment by snarfed** [comment]
ok! feel free to add the PR here and close!

**Comment by dshanske** [comment]
Fixed in #119
