### ISSUE TITLE
Error: {"error":"parameter_absent","error_description":"Missing Parameter: redirect_uri"}

### ISSUE THREAD

**Issue by kimberlyhirsh** [snarfed/wordpress-micropub#137]
I'm getting this error using Micropub with IndieAuth, even when all other plugins are deactivated. I've filed an issue on the IndieAuth for WordPress repository, too.

**Comment by snarfed** [comment]
thanks for filing @kimberlyhirsh, and sorry for the trouble! which micropub client is giving you this error?

**Comment by kimberlyhirsh** [comment]
All of them. The first one I noticed was OwnYourGram. I've also gotten it from Quill, indiebookclub.biz, and micropub.rocks.

**Comment by kimberlyhirsh** [comment]
I should add that there is always a redirect_uri in the address in my browser bar when I get it.

**Comment by snarfed** [comment]
from @dshanske in https://github.com/indieweb/wordpress-indieauth/issues/53#issuecomment-405306242 :

> But clearly, by @kimberlyhirsh statement, it is happening even with Indieauth.com, which suggests something browser side.

...so i'm tentatively closing this issue to avoid duplicating conversations.
