### ISSUE TITLE
unit tests!

### ISSUE THREAD

**Issue by snarfed** [snarfed/wordpress-micropub#14]
i'm not using this regularly myself, so if we're going to keep developing it, i'd like to have unit tests to give me confidence in our changes. @voxpelli pointed out these repos with good boilerplate and examples for phpunit + wp unit tests:

* https://github.com/frozzare/wp-plugin-boilerplate
* https://github.com/frozzare/wp-test-suite
* https://github.com/twitter/wordpress

the right level to test at is probably HTTP requests, ie the tests should construct top-level HTTP requests with different params and headers for each use case, send them to wordpress (within the same PHP runtime, not running WP as a server separately), and then check that they get the expected responses and that the right data is in the db.

cc @dshanske. excited!

**Comment by snarfed** [comment]
found a better tutorial: https://pippinsplugins.com/unit-tests-wordpress-plugins-introduction/. shows how to set up phpunit, wp-cli, a dedicated test db, and some built in tools for testing.

in our case, most of our tests will populate `$wp` and `$_POST`, call `Micropub::parse_query`, and then check the response and the posts in the db.

**Comment by voxpelli** [comment]
Think I will dive in here and see what I can do – try to make a PR that sets up the basics so that eg. @dshanske can rebase any PR of his on top of that to get some tests for his changes in.

**Comment by voxpelli** [comment]
After giving this a quick look I think @dshanske might be better of getting it set up than me right now. I might revisit this in the future though if there's still a need for it

**Comment by dshanske** [comment]
I am back to working on this. Refactoring parts of the code so that it is easier to identify the failing portion.
