### ISSUE TITLE
Repost post ype

### ISSUE THREAD

**Issue by metbril** [snarfed/wordpress-micropub#146]
A `like` by Quill will save as post kind `like` and post type `link`. This is as expected.

A `repost` by Quill (and Micropublish.net btw), will save as post kind `repost` and post type `standard`. This is rendered by SemPress with a title, which it shouldn't. I should at least be `aside` or something more appropriate.

**Comment by dshanske** [comment]
This is an issue you should file against Post Kinds, not Micropub.

**Comment by metbril** [comment]
https://github.com/dshanske/indieweb-post-kinds/issues/201
