### ISSUE TITLE
Error with Indigenous reader

### ISSUE THREAD

**Issue by jackjamieson2** [snarfed/wordpress-micropub#147]
Experiencing an error after logging in with indigenous for ios (https://github.com/EdwardHinkle/indigenous-ios). 

[07-Aug-2018 20:55:33 UTC] PHP Notice: Undefined index: content-type in /.../wp-content/plugins/micropub/micropub.php on line 1236 

[07-Aug-2018 20:55:33 UTC] Micropub Data: {"micropub":"endpoint","q":"config"} {"micropub":"endpoint","q":"config"}

**Comment by jackjamieson2** [comment]
(tagging @EdwardHinkle just in case)

**Comment by snarfed** [comment]
thanks for the logs! those don't actually show an error though. what user-visible symptom are you seeing? and which version of the plugin is this? and are you using the indieauth plugin too? which version if so?

**Comment by jackjamieson2** [comment]
Thanks @snarfed!

The user-visible symptom is that Indigenous should display a list of my microsub channels, and does not.  My logs indicate that it reaches my microsub endpoint with a valid request. The other microsub clients I've tested (Monocle and Together) do not have this issue.  

I'm using micropub 1.43, and Indieauth 3.1.2 

Thought it might be related to micropub because of the php notice, but maybe I'm wrong. Hopefully i can get time to troubleshoot it further in the next day or two and figure out where the problem lies

**Comment by snarfed** [comment]
yeah the php notice, and micropub in general, should be unrelated. sounds like an indigenous thing. you may want to file an issue there.

**Comment by dshanske** [comment]
I am working to do checks on all indexes to avoid this, but likely not related

**Comment by jackjamieson2** [comment]
Thanks! 

Filed an issue with indigenous: https://github.com/EdwardHinkle/indigenous-ios/issues/224
