### ISSUE TITLE
Reposts as post format 'standard' instead of 'link'

### ISSUE THREAD

**Issue by metbril** [snarfed/wordpress-micropub#151]
Reposts created with [Quill](https://quill.p3k.io/repost) get a **post kind** of [repost-of(https://indieweb.org/repost) , but the **post format** is `standard`. This makes the [post kinds plugin](https://github.com/dshanske/indieweb-post-kinds) not properly showin the post. The post kind `link` should be used instead.

**Comment by dshanske** [comment]
@metbril Micropub does not set post formats. Post Kinds hooks into Micropub posts and tries to set things based on parameters.

**Comment by metbril** [comment]
So the post kinds plugin should use a different post format for reposts? 

I don't know where in the chain of events thing happen, but when a post created by Micropub is saved (for the first time), both the proper post kind and format should be selected. Can you tell if this is possible at all and which plugin should dot this? If needed I will submit an issue in the appropriate repo.
