### ISSUE TITLE
Strange addition to Twitter cross-post

### ISSUE THREAD

**Issue by vishae** [snarfed/wordpress-micropub#154]
Currently using the bridgy plugin (Version 1.4.2) to cross post to Twitter. Today, when I tried posting something on my website, I see the following added to my Twitter post:

`html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd …" `

You can see the twitter post here: https://twitter.com/vishae/status/1030769594246619137

**Comment by snarfed** [comment]
hmm! interesting. sorry for the trouble!

in your HTML for that post, you have this between the text and the picture:

```html
<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\" \"http://www.w3.org/TR/REC-html40/loose.dtd\">
```

I'm guessing some plugin is adding it? it doesn't show up in the browser, but it does get parsed by microformats2 parsers and included in the content. @aaronpk @zegnat @tantek should it?

**Comment by Zegnat** [comment]
This would make for an interesting test to run on all the parsers…

As always, the HTML specification [holds the answer](https://html.spec.whatwg.org/multipage/parsing.html#parse-error-incorrectly-opened-comment):

> All content that follows the "`<!`" code point sequence up to a U+003E (>) code point (if present) or to the end of the input stream is treated as a comment.

HTML comments are not part of `textContent` so this string should not be showing up in any parsed plain-text content. (See, that wasn’t too tricky :wink:)

The real interesting question is whether this should be showing up in the `html` of an `e-` property… Currently it looks like the PHP parser is making it disappear. This would require more testing and discussion.

**Comment by Zegnat** [comment]
Note that, even though this shouldn’t be getting included, that doesn’t mean the original HTML is correct. It includes not only a `DOCTYPE` within its `<body>`, but also another `<html>` element (with matching `<body>` element) following it. This could be throwing off some HTML parsers.

**Comment by vishae** [comment]
sorry @snarfed, it seems I've located the issue (well, started to anyway). Apparently this is added in by the SemPress theme - I was previously using Independent Publisher and it didn't have this problem.

I'll just have to dig through SemPress to see what is causing this.

**Comment by snarfed** [comment]
> Edit: I just read the other comments. Are you saying that it's doesn't matter that the theme is adding the !DOCTYPE comment, but that the plugin shouldn't be showing it regardless?

kind of, yes. sempress shouldn't emit that strong (i think), but bridgy should also ignore it. that would happen in bridgy's mf2 parser, though, which will take a while, so your best bet for now is still to fix sempress!

**Comment by dshanske** [comment]
Closing as not a Micropub issue per se.
