### ISSUE TITLE
Published Dates Get Reset on Edit

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#16]
It appears it isn't coming from the client. Thinking the logic of create/edit needs to be reviewed after the specification is finalized to figure out what is resetting it.

**Comment by snarfed** [comment]
yup, we're not setting a `published` value in the `$args` that we pass to `wp_update_post`, but it's still setting it to the current time. i guess we need to read it from the post and set it to the original value ourselves.
