### ISSUE TITLE
Marking up Content vs Not

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#17]
I've been thinking about this. There are two modes the plugin works in.

1. Marks up the Content
2. If the theme supports microformats2(current_theme_supports) then it doesn't mark up the content.

I'm starting to think the conditional might be a mistake. If the theme supports microformats2, you still might want Micropub to mark up the content, as opposed to letting something else do it.

Then, what happens if you change your mind and want to switch themes, or switch options?

I'm not sure what the right move is here. Wanted to throw it open for consideration.

**Comment by snarfed** [comment]
[discussed on IRC.](http://indiewebcamp.com/irc/2015-08-25#t1440563470742) tentative conclusion is that this may be [YAGNI](https://indiewebcamp.com/YAGNI) and it's probably ok as is, without an explicit setting. we can always revisit later though!

**Comment by dshanske** [comment]
I have come up with a solution to this in the course of my rewrite to make unit testing possible. generating post content becomes a function attached to the after_micropub hook and therefore can be removed by another plugin.

**Comment by snarfed** [comment]
looks like we can close this now...?

**Comment by snarfed** [comment]
we now always auto generate content if it wasn't explicitly included in the micropub request. if it was, and if the theme supports `microformats2`, then we skip auto generating.

tentatively closing. feel free to reopen!
