### ISSUE TITLE
Plugin based on WP-API

### ISSUE THREAD

**Issue by pfefferle** [snarfed/wordpress-micropub#2]
BTW. Here is an example how to build a plugin, completely based on WP-API https://github.com/swissspidy/oEmbed-API

**Comment by snarfed** [comment]
thanks for looking at this so fast! i'm adding you as a collaborator.

would you like to check in WP-API and try some first steps modifying it toward micropub? i haven't started coding yet, so you're welcome to if you want!

**Comment by pfefferle** [comment]
Thanks, I will help where I can but you are too fast for me :)
