### ISSUE TITLE
Broken README.md

### ISSUE THREAD

**Issue by pfefferle** [snarfed/wordpress-micropub#241]
It seems that wp2md is breaking the Markdown. An example: https://github.com/indieweb/wordpress-micropub#masterhttpstravis-ciorgindiewebwordpress-micropub

What about adding the same Grunt task, we use for the Webmention plugin?

**Comment by dshanske** [comment]
Not objecting, just never put grunt into this project.

**Comment by dshanske** [comment]
Closed via 6eead252cb27c28d10d142bc20bf3700ea1ec399
