### ISSUE TITLE
Handle PHP 5.6 incompatibility

### ISSUE THREAD

**Issue by snarfed** [snarfed/wordpress-micropub#286]
From #285:

> Does the code maybe no longer support PHP 5.6? ...Confirmed, the last merged PR (https://github.com/indieweb/wordpress-micropub/pull/282) did the same thing, passed on PHP 7.2 but failed on 5.6: https://github.com/indieweb/wordpress-micropub/actions/runs/3175919981
>
> So we'll probably want to either raise the required PHP version or fix that incompatibility

Full error text:
```
PHP Parse error:  syntax error, unexpected '[' in /home/runner/work/wordpress-micropub/wordpress-micropub/includes/class-micropub-endpoint.php on line 719
```

cc @dshanske

**Comment by dshanske** [comment]
Resolved via #287
