### ISSUE TITLE
fix style issues reported by PHPCS

### ISSUE THREAD

**Issue by snarfed** [snarfed/wordpress-micropub#32]
_very_ low priority, since the big style stuff is ok now - tabs for indents, spaces inside parens, braces around `if`/`elseif` blocks.

[PHPCS details in the readme.](https://github.com/snarfed/wordpress-micropub#development) [WordPress coding standards here.](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards)

**Comment by snarfed** [comment]
hey @dshanske, to start, would you mind pasting in the full current PHPCS output here? i haven't set it all up, but i'd love to see the results!

**Comment by dshanske** [comment]
[phpcsmicropub.txt](https://github.com/snarfed/wordpress-micropub/files/353575/phpcsmicropub.txt)

**Comment by dshanske** [comment]
Figured that before I started messing around, might as well address this as it causes major changes in file structure.

**Comment by snarfed** [comment]
we looked at incorporating the PHPCS style suggestions in #51, and it didn't go so well. way too many false positives, not many actually useful suggestions. i'm going to tentatively close this.
