### ISSUE TITLE
HTTP "authorization" header not accepted (case-sensitive)

### ISSUE THREAD

**Issue by cweiske** [snarfed/wordpress-micropub#34]
HTTP headers are meant to be processed case-insensitive, but the code only accepts `Authorization` (word case) and not `authorization` (lowercase).

**Comment by cweiske** [comment]
@snarfed: Should I adjust `getallheaders()` or lowercase its result in `authorize()`?

**Comment by voxpelli** [comment]
The `getallheaders()` seems to already run a `strtolower()`? https://github.com/snarfed/wordpress-micropub/blob/f91bd8c88a1e2ad0399745537ab7aa442d04a3aa/micropub.php#L555

**Comment by snarfed** [comment]
true! the bug is probably just that `'Authorization'` [here](https://github.com/snarfed/wordpress-micropub/blob/master/micropub.php#L131) should be `'authorization'`.

**Comment by cweiske** [comment]
here in my local installation, the micropub-provided getallheaders is not used. So while the mp-provided getallheaders `Word-Cases` the header names (thus `Authorization` would work), the one that's actually used does not.

**Comment by cweiske** [comment]
Ah. PHP itself defines it. http://php.net/getallheaders

**Comment by cweiske** [comment]
So lowercasing the result of this function is the correct way.
