### ISSUE TITLE
git tags missing

### ISSUE THREAD

**Issue by cweiske** [snarfed/wordpress-micropub#39]
The versions released on wordpress don't have any tag in git.

**Comment by snarfed** [comment]
true! releases are infrequent, and commit volume is low and still pretty easy to skim to find releases, so tags haven't been a priority. happy to start though.

**Comment by cweiske** [comment]
```
$ git tag v0.2 2981bfc
$ git tag v0.3 e7e34e4
$ git tag v0.4 68bd134
$ git push --tags
```

**Comment by snarfed** [comment]
done! thanks for the nudge; apologies for the delay.
