### ISSUE TITLE
totally broken

### ISSUE THREAD

**Issue by cweiske** [snarfed/wordpress-micropub#40]
The plugin is currently total broken; every try to post returns a wordpress HTML error page.

git bisect told me:
```
$ git bisect good
ac82cba16b6cb109db9dea38fedb176bfb15304d is the first bad commit
commit ac82cba16b6cb109db9dea38fedb176bfb15304d
Author: Ryan Barrett <git@ryanb.org>
Date:   Wed Jun 29 12:02:20 2016 -0700

    switch from exit to wp_die()
    
    makes unit testing easier. also misc style tweaks.
```

And indeed, this is the first commit that breaks.

A successful request now returns:
```
HTTP/1.1 500 Internal Server Error
Date: Wed, 07 Sep 2016 19:15:03 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.19
Link: <http://wordpress.bogo/?micropub=endpoint>; rel="micropub"
Link: <http://anoweco.bogo/auth.php>; rel="authorization_endpoint"
Link: <http://anoweco.bogo/token.php>; rel="token_endpoint"
...
<body id="error-page">
	<p>Unknown WordPress error: 0</p></body>
</html>
```

**Comment by snarfed** [comment]
thanks for reporting. [discussing in IRC now.](https://chat.indieweb.org/2016-09-07#t1473275516730000)

**Comment by cweiske** [comment]
idea: the micropub plugin probably should register its own wp_die handler when it's running, and then would also have a place where to output the error json thingies

**Comment by voxpelli** [comment]
I can't find see anything that looks wrong with the changes in the mentioned commit – the `Unknown WordPress error` means that the save failed, but no reason why it failed.

Doesn't look to me like the `wp_die()` is to blame here.

**Comment by cweiske** [comment]
@voxpelli - the posts are created, but the server reply is broken.

**Comment by voxpelli** [comment]
@cweiske That's odd as [this line](https://github.com/snarfed/wordpress-micropub/blob/8aca05a86878bb020d6d99b5eeba825b0a96e239/micropub.php#L216) saves the post and [then checks](https://github.com/snarfed/wordpress-micropub/blob/8aca05a86878bb020d6d99b5eeba825b0a96e239/micropub.php#L514) whether the result of the post save is an error object or `0` and if it is, then that means there was a save error [according to WP docs](https://developer.wordpress.org/reference/functions/wp_insert_post/#return).

So unless `wp_insert_post()` is working in a different way than the docs are saying, then you shouldn't get that response on a successful save.

To aid further in development though it would be helpful to extend the `check_error()` method to also print a stack trace so that it can be determined which call to `check_error()` it is that is determined to provide an error.

**Comment by cweiske** [comment]
The `header()` call following "this" line does not stop output, but the `wp_die()` at the end of the method  is called at last.

That `wp_die()` does not get any error message or error code, which leads to ... "Unknown WordPress error: 0".

**Comment by voxpelli** [comment]
@cweiske The `wp_die()` itself does not print any error message, so unless `check_error()` is called the `Unknown WordPress error: 0` can't be printed as far as I can see – and since it prints a `0` in the message that also means that the input into the method that prints it is not `null` but rather an explicit `0`, which also shows that it can't be the `wp_die()` that causes it.

**Comment by snarfed** [comment]
i'm seeing the same problem locally with the code at head. evidently calling `wp_die` with no parameters crashes, even though the WP docs say that all params are optional. (here's where i admit that i don't actually know PHP. :P)

the WP docs also do say that `wp_die` "conditionally" prints an HTML error message - https://codex.wordpress.org/Function_Reference/wp_die#Description - but i don't see how to control that.

whee. so at minimum, we need to always pass `wp_die` params, and probably stop calling it in the success code paths, and maybe everywhere. ugh.

ok! let's figure out something that will work for both unit tests and real HTTP requests.

**Comment by voxpelli** [comment]
Looking at [the source code](https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/functions.php#L2539) of `wp_die()` it would certainly support an empty call as that would just result in `$message` becoming `''` and then passed to https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/functions.php#L2593, which prints it at https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/functions.php#L2617

**Comment by snarfed** [comment]
ah, thanks, you're right, i misinterpreted its default 500 response code.

**Comment by snarfed** [comment]
btw thanks for the source pointers @voxpelli! looking farther down in `wp_die`'s source, it evidently always prints the HTML page: https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/functions.php#L2642 . i don't see any way to tell it not to. so i guess either the plugin needs to install its own handler, which doesn't seem great, or we need something entirely different.

**Comment by snarfed** [comment]
btw, for posterity, the current released version of the plugin in the WordPress directory works fine. it's just the code at head here that's currently broken.

**Comment by dshanske** [comment]
What did we do?

**Comment by snarfed** [comment]
@dshanske read the issue. :P

**Comment by dshanske** [comment]
I thought I had used it since that change.

**Comment by cweiske** [comment]
Still broken:

```
./bin/shpub.php -s wp-local like www.bogo
Error: Server sent no "Location" header and said:
Fatal error: Class name must be a valid object or a string in /home/cweiske/Dev/tools/wordpress-micropub/micropub.php on line 531
```

This is `check_error()`

**Comment by snarfed** [comment]
@cweiske true! sorry, i should test with more than just curl and manual inspection.

**Comment by cweiske** [comment]
Why do you use that $cls instead of `static::`?

But even after adding the `$cls` definition to `check_error` it still does not work because the success call does not contain a message: `$cls::respond($status)`.

**Comment by snarfed** [comment]
> Why do you use that $cls instead of static::?

yeah, i know that is weird, good question. it's for the `Recorder` subclass of `Micropub` in the unit tests, which records the output status and body. i used to depend on `wp_die` for that, but without that, i haven't found a different way that works consistently, even including output buffering and the `status_header` filter. i'm open to ideas, if you have any!

and thanks for the pointer to shpub! i tried to set it up last night, and got close, but i was surprised that running `phing` complained that it didn't have the deps. e.g.

```sh
phing
Buildfile: /Users/ryan/src/shpub/build.xml

shpub > collectdeps:

   [delete] Directory /Users/ryan/src/shpub/lib does not exist or is not a directory.
    [mkdir] Created dir: /Users/ryan/src/shpub/lib

BUILD FAILED
/Users/ryan/src/shpub/build.xml:62:26: PEAR package pear.php.net/Console_CommandLine does not exist
Total time: 0.3549 seconds
```

i can install them all manually with `pear`, but i figured `phing` would do that automatically? apologies in advance, php tools are new to me.

**Comment by cweiske** [comment]
@snarfed - phar file of shpub 0.0.5 can be downloaded from https://github.com/cweiske/shpub/releases/tag/v0.0.5
