### ISSUE TITLE
1.0 seemed to have broken the WordPress way of storing geodata

### ISSUE THREAD

**Issue by lostfocus** [snarfed/wordpress-micropub#46]
As far as I can tell, [this here](https://indieweb.org/WordPress_Data#Location) seems to not work anymore. The code in the plugin looks good to me, though.

**Comment by derhess** [comment]
I am sorry to inform you that I have problems with version 1.0, too. The Micropub Update broke my current Wordpress installation (WordPress 4.6.1 running HyperX theme). After re-installing the plugin I get the same PHP error as I got when I have updated the plugin.

> Plugin could not be activated because it triggered a fatal error:
Parse error: syntax error, unexpected '[' in /kunden/146810_61239/webseiten/wp-content/plugins/micropub/micropub.php on line 826

I hope that helps a little bit...

**Comment by snarfed** [comment]
sorry for the problems, all, and thanks for the reports!

@derhess, sounds like you're on PHP 5.3 or older. i accidentally let a PHP 5.4-ism creep in. i'll cut a release with the fix today.

@lostfocus, the new version of the plugin changed the way it stores post metadata like geodata, and it now requires wordpress 4.4 or newer. are you maybe on an older version?

**Comment by snarfed** [comment]
@lostfocus i double checked with http://quill.p3k.io/ just now against my site https://snarfed.org/, and it stored location in the `geo_latitude` and `geo_longitude` post meta values ok.

**Comment by snarfed** [comment]
@derhess i pushed v1.0.1 to the wordpress plugin directory just now with a fix for your problem. thanks agan for reporting!

**Comment by lostfocus** [comment]
Aww, bummer. I've been testing on both my production and my development machine, which are identical most of the time - so it must be something with my config there. I'll update you if it's something worth mentioning.

**Comment by derhess** [comment]
@snarfed thank you very much for lightning fast fix! Everything works again on my PHP 5.3 env! Thanks!!
