### ISSUE TITLE
Update causing issues?

### ISSUE THREAD

**Issue by davidmead** [snarfed/wordpress-micropub#47]
Hi @snarfed.

Around the same time of the update my posts from Instagram are returning errors where the image should be. Also Twitter syndication using @dshanske's Bridgy Publish doesn't seem to be working.

Have you heard of these issues from anyone else?

You can see the issues at [my blog](http://davidjohnmead.com/blog/2016/10/29/something-is-broken/).

**Comment by snarfed** [comment]
hi! yes, i think @dshanske is aware that his syndication links plugin isn't compatible with the new micropub 1.0 release.

[neilpdx was right in IRC](https://chat.indieweb.org/2016-10-29#t1477767391527000); changing `WP_DEBUG` to `false` in your `wp-config.php` should prevent the visible errors.

as for twitter syndication with bridgy publish, that should be unrelated to wordpress-micropub. happy to hear more details, feel free to jump into IRC!

**Comment by dshanske** [comment]
The issue is a change in storage. I am going to adapt as my plugins handle display and Micropub only does storage. I'm not tied to not having it as an array.

**Comment by dshanske** [comment]
Both plugins need to be updated to work with the storage format change. I'm going to do that as soon as I can.

**Comment by snarfed** [comment]
sgtm. feel free to reopen if i can help!

btw @davidmead, you can fix at least the OwnYourGram problem by downgrading your wordpress-micropub plugin back to 0.4.

**Comment by davidmead** [comment]
Thanks @snarfed. I'll downgrade the micropub plugin. Look forward to the updates @dshanske when you get time :-)
