### ISSUE TITLE
Support setting of a textual address

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#48]
Support the option of saving a plaintext location property into geo_address.

**Comment by snarfed** [comment]
sure! was there a conclusion [on IRC today](https://chat.indieweb.org/2016-12-29/1483049630785000) as to where it would come from? i couldn't easily tell.

**Comment by dshanske** [comment]
If the location property is plaintext and not a nested property, URL, or geo URI

**Comment by snarfed** [comment]
hey @dshanske, mind trying this out to see if it works for you?

**Comment by snarfed** [comment]
tentatively closing.
