### ISSUE TITLE
Post Status and Visibility

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#49]
https://indieweb.org/Micropub-extensions#Post_Status 

As Quill at least now supports this, worth supporting, you think?

Post Status

*post-status=published (or no post-status set) - The post is published, or when the published date is in the future, the post is scheduled.
* post-status=draft - The post is a draft, and should not be shown in lists. (Of course it's up to the implementation whether it wants to use a capability URL for draft posts or actually restrict it to logged-in users.) 

Visibility

* visibility=public (or no visibility set)
* visibility=private

**Comment by snarfed** [comment]
sure, sounds great! want to send a PR?

**Comment by dshanske** [comment]
I will. I need to do some tests with Micropub anyway for the location thing.

**Comment by dshanske** [comment]
Noting the Micropub proposal to WordPress mappings

publish = (visibility = public) & (post-status=published)
draft = (post-status=draft) & (visibility=public)
private = (post-status=draft) & (visibility=private)

**Comment by snarfed** [comment]
thanks again for doing this @dshanske! closing.
