### ISSUE TITLE
Allow for a Local Authorization and Token Endpoint

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#5]
Add the ability to authorize using a local endpoint that authenticates locally instead of Indieauth.com

**Comment by snarfed** [comment]
totally!

**Comment by snarfed** [comment]
cc @pfefferle, who suggested adding a hook so that people could plug in their own alternative token endpoint. good idea! (we'd probably extract the token from the header/param and pass it in as an arg.)
