### ISSUE TITLE
clean up PHP warnings

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#50]
I noticed this in the log...Something tried to pull from my endpoint..not me...it shouldn't generate notices. May try to fix this.

017/01/03 07:59:04 [error] 6832#6832: *12666 FastCGI sent in stderr: "PHP message: Micropub Data: a:1:{s:8:"micropub";s:8:"endpoint";} a:1:{s:8:"micropub";s:8:"endpoint";}
PHP message: PHP Notice:  Undefined index: authorization in /srv/html/tiny.n9n.us/wp-content/plugins/wordpress-micropub/micropub.php on line 882
PHP message: PHP Notice:  Undefined index: access_token in /srv/html/tiny.n9n.us/wp-content/plugins/wordpress-micropub/micropub.php on line 157" while reading response header from upstream, client: 123.125.71.20, server: tiny.n9n.us, request: "GET /?micropub=endpoint HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "tiny.n9n.us"

**Comment by dshanske** [comment]
I've been looking at this one. These lines relate to Quill doing a GET request for ?q=config 

The plugin tries to authenticate for a config query. The specification is unclear as to whether that is required. But the issue comes

 $auth  = static::get_header( 'authorization' );
$token = $_POST['access_token'];

If there is not an access_token in the post, this generates an error.

**Comment by snarfed** [comment]
yup, common pattern in this plugin, and PHP in general. i've cleaned up many similar issues in the micropub plugin, but not these in particular. low priority.

**Comment by dshanske** [comment]
I will likely try after the other PR is done.

**Comment by dshanske** [comment]
Resolved.
