### ISSUE TITLE
"bookmark" posts require a title/content

### ISSUE THREAD

**Issue by cweiske** [snarfed/wordpress-micropub#58]
My tt-rss-micropub plugin creates bookmarks with only the `bookmark-of` property set. The wordpress micropub endpoint then returns an error, declaring that

> Content, title, and excerpt are empty.

We had this for "like" posts already in #41. Is there a reason that bookmark posts do not work with the URL only?

----

(Followup to https://github.com/cweiske/tt-rss-micropub/issues/1)

**Comment by snarfed** [comment]
hey, thanks for filing, and sorry for the trouble! cc @miklb. i can definitely add `bookmark-of` support.

i'm not sure if i have a more general fix, though. wordpress does indeed require at least one of content, title, or excerpt, but as you note, many micropub posts omit those, and depend on the server to render them appropriately. i don't yet have a good way to render arbitrary mf2 data, so i may need to just add support for individual properties like this as they come up.

**Comment by miklb** [comment]
I think the combination of semantic linkbacks and post kinds would handle it if the tt-rss plugin passed those to the micropub endpoint.

At least from my brief testing with Quill that's been the case.

**Comment by snarfed** [comment]
afaik semantic-linkbacks is just for incoming webmentions (replies, likes, etc), not posts.

**Comment by dshanske** [comment]
Post Kinds tries to handle it, yes

**Comment by snarfed** [comment]
broader discussion around this in https://github.com/pfefferle/SemPress/issues/51#issuecomment-303311143

**Comment by cweiske** [comment]
Ok, so the main problem is that bookmarks are not supported at all :)
