### ISSUE TITLE
automatically add post title if one isn't provided

### ISSUE THREAD

**Issue by snarfed** [snarfed/wordpress-micropub#61]
...ideally user configurable, since some users (and some plugins/themes) will want title, but others won't.

feature request from @anomalily at IWS 2017!

**Comment by lvnilesh** [comment]
Is it possible today to include publishing a post title? How would one expand on this?
```
curl -i $micropub_endpoint -H "Authorization: Bearer $access_token" \
  -H "Content-Type: application/json" \
  -d '{"type":"h-entry","properties":{"content":[{"html":"<p>Streaming Live</p>[videojs_hls url=\"https://domain.com/hls/key.m3u8\" autoplay=\"true\" controls=\"true\" preload=\"metadata\" inline=\"true\"]"}]}}' \
```

**Comment by snarfed** [comment]
@lvnilesh yes, it's definitely possible today to include a post title. just add the `name` mf2 property, e.g.:

```sh

1
--
curl -i $micropub_endpoint -H "Authorization: Bearer $access_token" \
  -H "Content-Type: application/json" \
  -d '{"type":"h-entry","properties":{"name": ["I'm live"], "content":[{"html":"<p>Streaming Live</p>[videojs_hls url=\"https://domain.com/hls/key.m3u8\" autoplay=\"true\" controls=\"true\" preload=\"metadata\" inline=\"true\"]"}]}}'
```

**Comment by snarfed** [comment]
...which begs the question. @anomalily, sounds like your request here was narrow. remind me, was it that OwnYourSwarm posts don't include an explicit title, so you were hoping to optionally generate a title automatically when the client (e.g. OYS) doesn't provide one itself?

**Comment by snarfed** [comment]
friendly ping @anomalily! do you remember the problem you told me about at IWS 2017 that inspired this issue?

**Comment by snarfed** [comment]
furthermore, notes actually don't have titles, so we'd definitely need more detail on what (if anything) this request actually is.

i'm tentatively closing it for now. feel free to reopen!
