### ISSUE TITLE
Wordpress' Post Format

### ISSUE THREAD

**Issue by svnsbck** [snarfed/wordpress-micropub#63]
Hi! I installed the plugin the other day and so far everything seems to work just fine. Great! But I was wondering is there a way to configure the plugin so that it uses the "Default" post format which is set by the user/me). At the moment it seems it is posting to the "Aside" format, whereas I would prefer to post it to the "Status" format, which I have configured in Wordpress' settings to be the standard. Is this something that is possible?

Any help appreciated.

**Comment by snarfed** [comment]
thanks for filling! good point. if i can look up the current default post type, it should definitely use that instead. will do.

**Comment by snarfed** [comment]
@svnsbck i looked into this, and we actually don't assign an explicit post format at all. i've added a unit test that checks this, and also tested manually on a local wordpress instance. could another plugin or theme maybe be affecting this in your instance?

**Comment by dshanske** [comment]
It is Post Kinds

**Comment by dshanske** [comment]
I'd like to find an issue I didn't cause

**Comment by snarfed** [comment]
lol, no worries @dshanske! thanks for letting us know. tentatively closing.
