### ISSUE TITLE
implement media endpoint

### ISSUE THREAD

**Issue by lvnilesh** [snarfed/wordpress-micropub#64]
https://micropub.rocks/server-tests/700?endpoint=107 

Wonder why all other tests pass but this one --> 700: Upload a jpg to the Media Endpoint

What is expected?
```
a JSON object with a media-endpoint property with the full URL of the endpoint
```
What is received?
```
HTTP/1.1 200 OK
Server: nginx/1.9.15
Date: Wed, 05 Jul 2017 22:34:29 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 19
Connection: keep-alive
X-Powered-By: PHP/7.1.2
Set-Cookie: PHPSESSID=02d7a88842f04e6221696077fc1c1b32; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Link: <https://tokens.indieauth.com/token>; rel="token_endpoint"
Vary: User-Agent
strict-transport-security: max-age=31536000
strict-transport-security: max-age=31536000

{
    "syndicate-to": []
}
```

What am I missing? 
Do I need to degine a media endpoint somewhere in my wordpress setup?
I would not locate any doc mentioning this. 

PS: I notice similar failure on tests 701 and 702

**Comment by snarfed** [comment]
good question! media endpoint is an optional micropub feature, not strictly necessary for anything, and this plugin doesn't support it (yet). so this isn't a failure, per se.

cc @aaronpk in case we want to make that clearer in micropub.rocks.

**Comment by lvnilesh** [comment]
Eddie seems to have implemented something but I could not locate the source. https://eddiehinkle.com/2017/06/29/2/article/

**Comment by snarfed** [comment]
spec section for media endpoint: https://www.w3.org/TR/micropub/#media-endpoint

**Comment by dshanske** [comment]
Resolved via https://github.com/snarfed/wordpress-micropub/commit/5737f6e62f9d901748e341d8e38475ec51d9ed21
