### ISSUE TITLE
Storing token information with each post

### ISSUE THREAD

**Issue by lostfocus** [snarfed/wordpress-micropub#67]
So, I've been thinking about finding a way of storing the token with each token - or at least the client_id. Am I missing something or would that require a pretty substantial rewrite?

**Comment by snarfed** [comment]
interesting! definitely possible. I'm curious why you'd want to though... what's your use case?

**Comment by lostfocus** [comment]
Mostly because I saw that @aaronpk is using a little "posted using [client]" line on his site and thought that'd be pretty nifty to have, too.

**Comment by snarfed** [comment]
ah. sure!

i see client_id in the auth flow, https://indieauth.com/developers, but that's between the micropub client and the user's sure/auth endpoint. i don't see client_id in micropub itself, https://www.w3.org/TR/micropub/, and this plugin isn't an auth endpoint, so it can't decode tokens. (and they're implementation-dependent anyway.)

@aaronpk's site is its own auth endpoint, so he has access to client_id. I'm not sure what we can do here.

**Comment by aaronpk** [comment]
How does this plugin verify access tokens?

**Comment by lostfocus** [comment]
Hm, at least with indieauth.com as a token endpoint the client_id should be in the token response. (Like 'me' which is used in [line 184](https://github.com/snarfed/wordpress-micropub/blob/v1.2/micropub.php#L184).) It might be possible to do something there.

**Comment by snarfed** [comment]
ooh, ok! we could definitely optionally grab client_id from the verify response if it's there.

(@aaronpk it does the standard indieauth verification, but the endpoint is user-configurable.)

@lostfocus interested in tackling this? should be straightforward!
