### ISSUE TITLE
Missing Location Header

### ISSUE THREAD

**Issue by miklb** [snarfed/wordpress-micropub#69]
Trying to post an image from Quill while traveling I got an error.

`400 Bad Request` 

```
{"error": "invalid_request", "error_description": "Sorry, this file type is not permitted for security reasons."}
```

Is this something with my server config or an issue with the plugin? Thanks!

![img_4300](https://user-images.githubusercontent.com/819716/28500414-d8ae3c58-6f95-11e7-9c22-e562b3c85cbc.jpg)

**Comment by snarfed** [comment]
heh, it actually 400ed. "This file type is not permitted for security reasons" is the key error message. (it comes from WordPress.) what's the image filename extension?

**Comment by snarfed** [comment]
one key bug report/feature request for quill here is probably that it should pay attention to non-2xx status codes before looking for the Location header. cc @aaronpk

**Comment by miklb** [comment]
>  what's the image filename extension?

Not sure, this was via iOS but I think they are just .jpg files.

**Comment by snarfed** [comment]
this error comes from wordpress itself, inside `media_handle_upload()`, not from the micropub plugin. i believe it has a whitelist of file extensions: https://codex.wordpress.org/Uploading_Files#About_Uploading_Files_on_Dashboard . `jpg` is definitely in the whitelist; maybe your file had a different extension?

**Comment by miklb** [comment]
Thanks @snarfed I will do a test now that I'm not traveling and submit the bug to Quill. I'll keep this open for now and report back what I discover in case anyone else gets tripped up by it.

**Comment by miklb** [comment]
Learned this evening that Quill sends a temp file name without an extension so surely that is the root of the error.

If it's not something that can be changed in Quill, I'll look for another mobile micropub client or a way to whitelist uploads from Quill.

**Comment by gRegorLove** [comment]
Related: https://core.trac.wordpress.org/ticket/40175

From my skimming, it sounds like WP core will try to rename a file if it's a whitelisted mime type and the extension doesn't match. Not sure if it just doesn't do that with extension-less files or not.

**Comment by snarfed** [comment]
added the whitelist to the docs. tentatively closing, since this is a wordpress internal thing i can't easily change. thanks again for filing @miklb!

**Comment by miklb** [comment]
If anyone comes across this, there is a [PR for Quill](https://github.com/aaronpk/Quill/pull/82) that should mitigate the problem.

**Comment by miklb** [comment]
Just an update, @aaronpk deployed the above mentioned PR, and the `400 Bad Request` error is gone, however the "Endpoint did not return Location Header" is still there.
