### ISSUE TITLE
Support Syndication Target Discovery

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#7]
The MicroPub plugin shouldn't support syndication. It should support discovering targets using a WordPress filter, which can be modified outside of the plugin. So, by default, it would return an empty list.

**Comment by snarfed** [comment]
delayed response: sounds good, I'd happily merge a PR for this!

**Comment by dshanske** [comment]
I wasn't trying to suggest anything when I mentioned it earlier. After I finish my current major rewrite of Post Kinds, I wanted to work on having it support Micropub through the action hooks you put in. I figured I'd send a few PRs your way then.

**Comment by snarfed** [comment]
sounds great! and no worries; i was just embarrassed i never responded in the first place.

**Comment by dshanske** [comment]
Address in #12
