### ISSUE TITLE
post_date_GMT is 1970-01-01 00:00:00 for some posts

### ISSUE THREAD

**Issue by lostfocus** [snarfed/wordpress-micropub#70]
#9 seems to be happening for me.
Weirdly enough only with [ownyourgram](http://ownyourgram.com/)/[ownyourswarm](https://ownyourswarm.p3k.io/) posts, it is working fine with [Quill](https://quill.p3k.io/). I'll do some more research.

**Comment by dshanske** [comment]
I had that problem in Semantic Linkbacks due php date functions and was able to address as an interim measure that if it couldn't parse the date, it would set to the present.

**Comment by lostfocus** [comment]
It's actually just a small bug. It doesn't happen with Quill because then it just assumes the present, while the ownyour* set the `published` property, which triggered the bug.

**Comment by snarfed** [comment]
thank you for filing @lostfocus, and for the fix!
