### ISSUE TITLE
Remove charset=utf-8 from Content header

### ISSUE THREAD

**Issue by miklb** [snarfed/wordpress-micropub#73]
As @aaronpk pointed out in [#indieweb-dev](https://chat.indieweb.org/dev/2017-08-27/1503863641444000) "Technically charset=utf-8 is unnecessary with JSON content type since JSON is utf-8 already"

See also: https://github.com/cweiske/shpub/pull/6

**Comment by snarfed** [comment]
interesting!

from https://tools.ietf.org/html/rfc7158#section-8.1 :
> JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32

...but from https://www.iana.org/assignments/media-types/application/json :
> Note:  No "charset" parameter is defined for this registration. Adding one really has no effect on compliant recipients.

...i assume since UTF variant can be determined from the first few bytes.

so yup, i'll remove charset. thanks for filing!
