### ISSUE TITLE
return error on unknown syndicate-to

### ISSUE THREAD

**Issue by snarfed** [snarfed/wordpress-micropub#78]
we currently support `syndicate-to` via other plugins, e.g. @dshanske's bridgy publish, but not built in. embarrassingly, we still happily accept all `syndicate-to` values, and silently drop them and still return success even if no other plugin handles them. this caused @miklb some confusion and unnecessary debugging today when he tried to hook wordpress micropub up to https://silo.pub/ .

when we get a request with `syndicate-to`(s), we should determine whether we have plugins installed that can handle them, probably with the `micropub_syndicate-to` filter, and return an error if any are unsupported.

apologies for the trouble, @miklb! thanks for raising it!

**Comment by dshanske** [comment]
I was just contemplating this. I may move some of the logic I implemented into the Micropub plugin. Specifically, if there is a syndication payload, then it can trigger a hook.

**Comment by snarfed** [comment]
feel free to try the new code at head @miklb! should now return HTTP 400 if you send a `syndicate-to` that it doesn't handle.

also, fwiw, other plugins can already handle micropub syndication via the `before_micropub` filter and `after_micropub` hook. that may be all we need, ie we may not need a separate new syndication hook.

**Comment by miklb** [comment]
I wondered if I could trigger the `after_micropub` to send my syndication. I might test that this weekend.
