### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by miklb** [snarfed/wordpress-micropub#79]
I think there have been some informal discussions, but testing [Indigenous](https://github.com/EdwardHinkle/indigenous-ios/) it would be handy to be able to look at `debug.log` or something in the admin to see failed micropub requests. (Or successful with the payload for other debugging needs).

Is this something you've considered or have any thoughts on? I'm not sure a full blown log viewer like this [Rest API log](https://wordpress.org/plugins/wp-rest-api-log/) is needed. 

Maybe just any response that doesn't return a `200` logs to `debug.log` ?

**Comment by snarfed** [comment]
definitely! it already logs a fair amount, including full query/post data for every request, if `WP_DEBUG` is true. try that?

**Comment by miklb** [comment]
Oh, I must have missed that. I’ll doublw check the debug file. Thanks!

**Comment by miklb** [comment]
So nothing must have come through from Indigenous as there's nothing in the logs, so a silent fail somewhere. I'll follow up with Eddie in the iOS app repo.

Thanks again.

**Comment by snarfed** [comment]
you can also check your web server's logs, e.g. `/var/log/apache2/access_log` and `error_log`.

**Comment by snarfed** [comment]
friendly ping, @miklb did you figure this out?

**Comment by miklb** [comment]
Sorry, yes, I should have closed this issue.
