### ISSUE TITLE
Rollback Special Casing of Checkins

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#81]
https://github.com/snarfed/wordpress-micropub/commit/96150015c48687ef96eab507a6a661d83de5b62c 

Being as in Post Kinds 2.7.0(bug fixes regarding markup to be made for 2.7.1 in the next day or so), handling of Checkins has been enabled, requesting this commit be rolled back.

**Comment by snarfed** [comment]
hey, sure!

that commit actually added checkin rendering for themes that declare support for `microformats2` as well as the post kinds plugin. i can disable it when post kinds is installed, at least. sound good?

**Comment by dshanske** [comment]
That is what I was asking, sorry.

**Comment by dshanske** [comment]
At least until we solve the other problem

**Comment by dshanske** [comment]
Looking at OYS, which started this, and https://ownyourswarm.p3k.io/docs, if your server doesn't know what a checkin is, then you should set OYS to simple and all checkins will post as notes. So, why not document that in the readme over the special override solution?

**Comment by snarfed** [comment]
> why not document that in the readme over the special override solution?

good question! because most users don't read docs or ever touch settings, so it's our job to make things Just Work as much as possible, out of the box, without requiring them to do anything special.

**Comment by dshanske** [comment]
Good point.

**Comment by snarfed** [comment]
done in #94.
