### ISSUE TITLE
Plugin Generates Post Content

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#82]
Plugin Generates Post Content if there isn't for any post, even if other plugins are installed. Being as the post content is a summary of the properties, wondering if this is always necessary and wanted to discuss how this can best be addressed, as if, for example, I'm displaying the property, I don't necessarily want the post_content as a copy of same.

**Comment by snarfed** [comment]
true! this is the same thing we've all been talking about for a while, though, right?

if i understand right, the long term plan is still roughly https://github.com/indieweb/wordpress-uf2/issues/30, but we haven't fully decided and committed (or implemented) yet...and short term, this plugin handles it by skipping generating post content if the current theme declares that it supports mf2 or the post kind plugin is installed:

https://github.com/snarfed/wordpress-micropub/blob/baf04969429f5ce592e21e972e26621bb99a8da7/micropub.php#L535-L537

has anything changed? or are there new plugins that render stored mf2 properties and duplicate content this plugin renders? should we just special case them like we currently do post kinds?

**Comment by dshanske** [comment]
My long term plan is to revisit the older design where I could unhook the automatic content generation by removing a filter.  But that is a much bigger PR. I'm hoping we settle the interoperability issue at some point, but that would allow me to unhook the extra stuff.

**Comment by snarfed** [comment]
i'm pretty reluctant to continue adding and changing and iterating wokarounds, when we know  the real solution we need to decide on and do.

the big work there isn't even code or a PR, though, it's working through the design details in https://github.com/indieweb/wordpress-uf2/issues/30 and making sure all the stakeholders agree. actually implementing it afterward will be easier.

still, that's where we should be putting our time and effort, not continuing to evolve workarounds.

**Comment by dshanske** [comment]
So, that said, we aren't doing that right now. I wish we could come to a good idea for it. In the meantime, I will probably split the pieces up, and try to implement in a better way long term.

**Comment by dshanske** [comment]
How would you feel if I better separated the post content generation from the Micropub plumbing? Then, regardless of what functionality we add later to decide how to engage the rendering, it is a separate piece?

**Comment by snarfed** [comment]
thanks for pushing on this!

i actually don't think we need any more ideas; there are plenty of good ideas in https://github.com/indieweb/wordpress-uf2/issues/30 already. we're just waiting for someone to take the lead, make sure all the stakeholders agree, and then lay out a plan and get everyone to do their part. you should take that lead!

as for separating content generation from micropub plumbing...sure, but that's pretty abstract. what's the specific user-visible feature or behavior you want it for that's not doable today?

again, i think we should put most of our time and effort into the long term solution, so i'm pretty unlikely to merge any other new workarounds that aren't clearly toward that. feel free to propose something if you want though.

**Comment by dshanske** [comment]
My hack day project linked into before_micropub to add a complete citation instead of just the URL to the input. If I do it after I post, it would go out differently to syndication.  Similar to the old Semantic Linkbacks problem. But Micropub doesn't recognize nested properties.

So, the auto presentation was messed up. Removing post content completely would prevent a post with no content and title per WordPress rules. The excerpt you do is really a summary anyway, and having an excerpt does allow empty title and content...

That's why all those things went together.

**Comment by dshanske** [comment]
You wanted to, regardless of switching, to move from static to dynamic generation. Would you accept PRs for that? The only sticking point is still implementing how the plugins work together.

**Comment by dshanske** [comment]
By making it dynamic, it can work with what I am doing regardless. I am storing the same properties Micropub i

**Comment by dshanske** [comment]
As I use Micropub more, I am coming up against the conflict, which makes me want to resolve it finally. I want to be able to work on a few area. And the three are too entangled right now. 

1. Authentication
2. Micropub properties to WordPress
3. Rendering
4. Queries

**Comment by snarfed** [comment]
> You wanted to, regardless of switching, to move from static to dynamic generation. Would you accept PRs for that? The only sticking point is still implementing how the plugins work together.

again, since there are multiple stakeholders, maintaining different plugins and themes that need to interoperate, "how the plugins work together" is *the* key point. we need to get all of the stakeholders to agree on that before writing code or PRs.

we've made a lot of progress on this in https://github.com/indieweb/wordpress-uf2/issues/30! we're most of the way there. we just need a leader to drive us to the finish. you should jump in!

> As I use Micropub more, I am coming up against the conflict, which makes me want to resolve it finally. I want to be able to work on a few area. And the four are too entangled right now.

sure! i assume they'd still all stay in the micropub plugin except some rendering parts? feel free to make a concrete design proposal, ideally before writing any new code.

**Comment by dshanske** [comment]
I don't want to split them into different plugins, just different pieces inside the same plugin.

**Comment by dshanske** [comment]
Then it is easier to work with each part without touching the other ones.

**Comment by dshanske** [comment]
https://www.w3.org/TR/micropub/#h-unrecognized-properties

**Comment by snarfed** [comment]
hey @dshanske i think #94 (merged) addressed this, right? shall we close this?

**Comment by dshanske** [comment]
It did.
