### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#84]
I considered the idea of building an authentication provider into the Indieauth plugin. Basically, right now, Micropub handles its own authorization. What if the Indieauth plugin handled authorization?

**Comment by dshanske** [comment]
https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/


Similar to these plugins that add authentication

**Comment by dshanske** [comment]
I am not talking about running a service. The Indieauth plugin delegates that to an outside service.

While I wouldn't mind having a local option, that is not what I am contemplating now.

**Comment by dshanske** [comment]
Even if it stays in this plugin, I would like its functionality to be separate and invoked as needed

**Comment by pfefferle** [comment]
cool! I hope they will add OAuth2 support soon!

**Comment by dshanske** [comment]
If they do, this plugin can use that too

**Comment by pfefferle** [comment]
that's what I meant :)
