### ISSUE TITLE
Need to set post date GMT?

### ISSUE THREAD

**Issue by aaronpk** [snarfed/wordpress-micropub#9]
I think the plugin is not setting the post_date_gmt field when creating the post. It looks like a new post that was created with the published date set in the micropub request has the gmt date set to 0.

**Comment by pfefferle** [comment]
Yes, you have to set the `post_date_gmt`. Here is an example how I implemented the WebMention/Linkback date: https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/master/semantic-linkbacks-microformats-handler.php#L147

**Comment by snarfed** [comment]
huh, odd. thanks @pfefferle! will do.

**Comment by pfefferle** [comment]
here is an example from the core https://github.com/WordPress/WordPress/blob/72f18cb0679c7e67460c1a86dcb62d71d58281f1/wp-admin/includes/post.php#L165

**Comment by snarfed** [comment]
huh, odd. fwiw, i'm not actually seeing this behavior with the current code. when i pass e.g. `published=2013-10-09T08:19:00-07:00` and then look at the resulting `wp_posts` row in the db, `post_date` is set to `2013-10-09 08:19:00` and `post_date_gmt` to `2013-10-09 15:19:00`, both of which seem correct.
