### ISSUE TITLE
use JSON response format for token check

### ISSUE THREAD

**Issue by aaronpk** [snarfed/wordpress-micropub#95]
The [IndieAuth spec](https://indieauth.net/spec/) uses JSON responses and form-encoded requests.

Can you add an `Accept: application/json` header [here](https://github.com/snarfed/wordpress-micropub/blob/master/micropub.php#L170) and change [this line](https://github.com/snarfed/wordpress-micropub/blob/master/micropub.php#L178) to use `json_decode` instead?

**Comment by snarfed** [comment]
yes! will do. @dshanske graciously volunteered to take this on.

**Comment by dshanske** [comment]
As a note, I want to look to implementing the spec more thoroughly anyway. Right now, there are some steps in the current version of the spec that are omitted that can be added in at the same time. Keep in mind, on some of those, the spec wasn't clearly written out when implemented, but is nicely written out now.

**Comment by snarfed** [comment]
ok! i _strongly_ recommend small separate PRs though. there's usually no meaningful benefit to doing multiple things in the same PR just because they touch nearby code, and PRs that do multiple things are harder to review.

**Comment by dshanske** [comment]
This can be closed.
