### ISSUE TITLE
IndieAuth Plugin and Micropub Plugin

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#96]
Since I'm working on IndieAuth support in the IndieAuth Plugin, invariably, we might end up with a conflict as I iterate. Wanted to open an issue to discuss possibilities.

https://github.com/indieweb/wordpress-indieauth/

1. Right now, Micropub preempts WordPress if the micropub query variable is set and launches into a completely different set of code, so it will not be affected by the code I have hooking into determine_current_user which duplicates the same functionality. 
1. It uses 'indieauth_token_endpoint' and 'indieauth_authorization_endpoint' as option names. Should be easy to look there and fall back on the declaration if they aren't set. 

I'm not sure if it is worth making it so Micropub uses the Indieauth plugin version of the code over the built in one.

**Comment by snarfed** [comment]
thanks for discussing ahead of time! all this analysis makes sense and sounds good to me.

**Comment by snarfed** [comment]
btw this looks similar to #85? let's maybe close one or the other.

**Comment by dshanske** [comment]
That is about mf2 whereas this is about Indieauth

**Comment by snarfed** [comment]
oops, sorry, i mistyped. i meant #84.

**Comment by dshanske** [comment]
It is, but now it has been done

**Comment by snarfed** [comment]
great! closed.
